version: 2.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    environment:
      COVERALLS_REPO_TOKEN
    steps:
      - checkout
      - run: 
          name: Restore packages
          command: 
            dotnet restore
      - run: 
          name: Build App
          command:
            dotnet build
      - run:
          name: Test
          path: "./CrptopalsChallenge.Test"
          command:
            dotnet test
      # - run:
      #     name: Code coverage
      #     command: COVERALLS_REPO_TOKEN= ${COVERALLS_REPO_TOKEN} bundle exec rspec
      # # Save test results for timing analysis
      # - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
      #     path: test_results
    notify:
      webhooks:
        - url: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
    post:
      - coveralls

